version: '3.9'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: db_spzx
      POSTGRES_PASSWORD: Hcf20001123
    ports:
      - "5432:5432"
  mysql:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: Hcf20001123
      MYSQL_DATABASE: db_spzx
    ports:
      - "3306:3306"

  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"