version: '3.9'

services:

  db:
    image: postgres
    restart: on-failure:3
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: db_spzx
      POSTGRES_PASSWORD: Hcf20001123
    ports:
      - "5432:5432"
  mysql:
    image: mysql
    restart: on-failure:3
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hcf20001123
      MYSQL_DATABASE: db_spzx
    ports:
      - "3306:3306"

  redis:
    image: redis
    restart: on-failure:3
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - "6379:6379"